version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: always
    environment:
      - CLIENT_TOKEN=${DISCORD_TOKEN}
    volumes:
      - .:/app  # Maps the local `bot` directory to `/app` in the container
    command: python index.py  # Adjust this to your bot's entry point